FROM python:3.11

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

ENV DATABASE_URL_POSTGRES=${DATABASE_URL_POSTGRES}
ENV DATABASE_URL_RICK_AND_MORTY=${DATABASE_URL_RICK_AND_MORTY}
ENV DB_NAME=${DB_NAME}
ENV FRONT_END_URL=${FRONT_END_URL}
ENV ENVIRONMENT=${ENVIRONMENT}

EXPOSE 5000
